language: python
install: pip install tox
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=py37
  - TOX_ENV=pypy
  - TOX_ENV=pep8

script: tox -e $TOX_ENV
notifications:
  email:
    - accts@jpainter.org
    - bm_witness@yahoo.com
